"""first_last and first name from being unique

Revision ID: bcecbd6edb52
Revises: 3b0059253179
Create Date: 2023-09-26 21:19:10.235932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcecbd6edb52'
down_revision = '3b0059253179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('first_name')
        batch_op.drop_index('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('last_name', ['last_name'], unique=False)
        batch_op.create_index('first_name', ['first_name'], unique=False)

    # ### end Alembic commands ###
